# Generated by Django 5.0.6 on 2024-06-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='username',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='employee_id',
            field=models.CharField(default='abcd', max_length=20, unique=True),
        ),
    ]
