# Generated by Django 5.0.6 on 2024-06-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0002_remove_leavebalance_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavebalance',
            old_name='leave_count',
            new_name='paid_leave',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='sick_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='unpaid_leave',
            field=models.IntegerField(default=0),
        ),
    ]
