# Generated by Django 5.0.6 on 2024-06-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0003_rename_leave_count_leavebalance_paid_leave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_leave', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_count', models.IntegerField()),
                ('leave_balance', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackbot.leavebalance')),
            ],
        ),
    ]
