# Generated by Django 5.0.6 on 2024-06-20 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0004_leavehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='slackbot.leavebalance'),
        ),
    ]
